In [103]:
import seaborn as sns
import pandas as pd
from scipy.stats import ks_2samp

In [104]:
vars = ["A","B","C","D","E","F"]

In [105]:
def analysis(path):
    dataframe = pd.read_csv(path, usecols= vars)
    means = round(dataframe.mean(axis=0),2)
    variances = round(dataframe.var(axis=0),2)
    corrs = round(dataframe.corr(),3)
    return dataframe, means, variances, corrs

In [106]:
def ks_2(df1, df2, vars, skip):
    alpha_bonf = 0.05/(len(vars)-1)
    print("Alpha_bonferoni correction:", alpha_bonf)
    
    for var in vars:
        if var != skip:
            result = ks_2samp(df1[var], df2[var])
            pvalue = result.pvalue
            if pvalue < alpha_bonf:
                print(f"{var} vs {var}: Null hypothesis is rejected with p-value {round(pvalue,4)}")
            else:
                print(f"{var} vs {var}: Null hypothesis can't be rejected with p-value {round(pvalue,4)}")

# Baseline

In [107]:
baseline, means, variances, corrs = analysis(r"data\baseline_200_samples.csv")
baseline

             A         B         C         D         E         F
0     7.034942  1.087211  0.071169  2.515805 -2.405473  2.544125
1     4.874421  0.124294  3.475943  1.908251 -2.194978  5.580401
2    -0.041795  4.268048 -0.156468 -0.383868 -2.102513  2.272098
3     4.392423  9.171482  0.882335 -2.262698 -0.076396  0.775761
4    15.811783  2.950558 -0.130275 -4.068523 -1.940396  1.988671
..         ...       ...       ...       ...       ...       ...
195   5.954162  0.261246 -1.246915 -2.178848 -0.988815 -0.236519
196   0.978385  0.749201  0.149997 -0.073741 -0.570527  0.725176
197  -0.363205  3.093016 -0.842518 -0.628412 -1.556955  0.852012
198   3.627813  6.830127  3.487210  1.591534 -2.064623  5.523399
199   3.793586  0.353433 -0.152282 -1.616998 -1.238985  0.893087

[200 rows x 6 columns]

In [108]:
means, variances

(A    7.87
 B    4.60
 C   -0.01
 D   -1.11
 E   -1.21
 F    1.21
 dtype: float64,
 A    226.13
 B     40.19
 C      2.70
 D      6.26
 E      0.88
 F      3.66
 dtype: float64)

In [109]:
corrs

       A      B      C      D      E      F
A  1.000  0.026 -0.064 -0.796 -0.007 -0.050
B  0.026  1.000  0.021 -0.057 -0.001  0.014
C -0.064  0.021  1.000  0.059 -0.016  0.865
D -0.796 -0.057  0.059  1.000 -0.239  0.161
E -0.007 -0.001 -0.016 -0.239  1.000 -0.500
F -0.050  0.014  0.865  0.161 -0.500  1.000

# Intervention D=2

In [110]:
intervention_D2, means, variances, corrs = analysis(r"data\intervention_100_D2.csv")
intervention_D2

           A          B         C    D         E         F
0   4.134824   1.589683  0.329446  2.0 -1.049140  1.281664
1   5.136066   0.188126  1.567321  2.0 -1.819315  3.392483
2   4.777690   5.386215 -0.895065  2.0 -1.025964 -0.253656
3   5.149620   0.090468 -0.920072  2.0 -1.465165  1.380897
4   5.048520  12.103582 -0.930709  2.0  2.599108 -3.692334
..       ...        ...       ...  ...       ...       ...
95  5.152641  12.520147  1.330054  2.0  0.650924  0.669306
96  4.844531   0.808172 -1.318542  2.0 -1.547973  0.087356
97  5.153170   0.032851 -0.732904  2.0 -1.240641  0.287877
98  5.128235   0.226201 -1.015948  2.0 -2.167671  0.988594
99  3.627963  10.441982 -0.489118  2.0 -1.571004  1.449090

[100 rows x 6 columns]

In [111]:
means, variances

(A    4.53
 B    4.54
 C    0.13
 D    2.00
 E   -1.23
 F    1.36
 dtype: float64,
 A     0.48
 B    38.47
 C     2.67
 D     0.00
 E     0.98
 F     3.36
 dtype: float64)

In [112]:
corrs

       A      B      C   D      E      F
A  1.000 -0.285  0.031 NaN -0.017  0.043
B -0.285  1.000 -0.108 NaN  0.070 -0.107
C  0.031 -0.108  1.000 NaN  0.080  0.833
D    NaN    NaN    NaN NaN    NaN    NaN
E -0.017  0.070  0.080 NaN  1.000 -0.466
F  0.043 -0.107  0.833 NaN -0.466  1.000

Kolmogorov-Smirnov

The null hypothesis is that the two distributions are identical

In [113]:
ks_2(baseline, intervention_D2, vars, "D")

Alpha_bonferoni correction: 0.01
A vs A: Null hypothesis is rejected with p-value 0.0
B vs B: Null hypothesis can't be rejected with p-value 0.3336
C vs C: Null hypothesis can't be rejected with p-value 0.0634
E vs E: Null hypothesis can't be rejected with p-value 0.9991
F vs F: Null hypothesis can't be rejected with p-value 0.2423

We reject the nullhypothesis for A, meaning that the distributions are not the same

# Intervention F=-2

In [114]:
intervention_Fminus2, means, variances, corrs = analysis(r"data\intervention_100_Fminus2.csv")
intervention_Fminus2

            A          B         C         D         E    F
0   13.742782   3.734497 -0.959642 -3.739310 -0.889059 -2.0
1    6.327587   1.007091 -0.203693 -2.281140 -0.678147 -2.0
2    6.630581   7.804673  0.325001  2.447780 -1.974182 -2.0
3    1.216969   5.390431  0.160311  0.005844 -0.074209 -2.0
4    1.414079   1.667067 -0.592465  0.959445 -0.957568 -2.0
..        ...        ...       ...       ...       ...  ...
95   8.069312   7.688808 -0.131682 -2.704667 -1.588221 -2.0
96   3.140370  19.481946 -4.624836 -1.320639 -1.095512 -2.0
97   8.653837  24.594201  0.222729  2.684346 -1.842177 -2.0
98   5.816730   2.910153 -0.389196  2.490061 -2.154842 -2.0
99   1.636673   0.208257  0.238823  0.261943 -1.822102 -2.0

[100 rows x 6 columns]

In [115]:
means, variances

(A    11.51
 B     4.00
 C     0.09
 D    -1.47
 E    -1.12
 F    -2.00
 dtype: float64,
 A    544.17
 B     26.83
 C      1.65
 D      8.56
 E      1.31
 F      0.00
 dtype: float64)

In [116]:
corrs

       A      B      C      D      E   F
A  1.000  0.095 -0.014 -0.807  0.398 NaN
B  0.095  1.000 -0.359 -0.015  0.079 NaN
C -0.014 -0.359  1.000  0.066 -0.027 NaN
D -0.807 -0.015  0.066  1.000 -0.551 NaN
E  0.398  0.079 -0.027 -0.551  1.000 NaN
F    NaN    NaN    NaN    NaN    NaN NaN

In [121]:
ks_2(baseline, intervention_Fminus2, vars, "F")

Alpha_bonferoni correction: 0.01
A vs A: Null hypothesis can't be rejected with p-value 0.0154
B vs B: Null hypothesis can't be rejected with p-value 0.9362
C vs C: Null hypothesis can't be rejected with p-value 0.5083
D vs D: Null hypothesis can't be rejected with p-value 0.2854
E vs E: Null hypothesis can't be rejected with p-value 0.8933